[package]
name = "portfolio_terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
futures = "0.3.31"
ratatui = "0.29.0"
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
